import "./globals.css";
import { Inter } from "next/font/google";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import NavigationBar from "./components/navigation";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "La Cocina de Todos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`min-h-screen flex flex-col ${inter.className}`}>
          <NavigationBar />
          <div className="flex-grow">{children}</div>
          <Footer />
        </body>
      </UserProvider>
    </html>
  );
}
